<a href="https://colab.research.google.com/github/yoonhyun123/AI/blob/main/numpy%2Cpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

list=[1,2,3,4]
a=np.array(list)
print('a.shape:',a.shape)
print('a[0]',a[0])

b=np.array([[1,2,3],[4,5,6]])
print('b.shape:',b.shape)
print('b[0,0]',b[0,0])
print('b[0]:',b[1])

a.shape: (4,)
a[0] 1
b.shape: (2, 3)
b[0,0] 1
b[0]: [4 5 6]


In [16]:
a=np.zeros((2,3)) #0인 n차원
print('a:\n',a)

b=np.ones((2,3)) #1인 n차원
print('b:\n',b)

c=np.full((2,3),7) #값 n차원
print('c:\n',c)

d=np.eye(2)   #단위행렬
print('d:\n',d)



a:
 [[0. 0. 0.]
 [0. 0. 0.]]
b:
 [[1. 1. 1.]
 [1. 1. 1.]]
c:
 [[7 7 7]
 [7 7 7]]
d:
 [[1. 0.]
 [0. 1.]]


In [18]:
a= np.array([1,2],dtype=np.float64)  #dtype 옵션을 추가하면 자료형 지정
print('a.dtype:',a.dtype)

b= a.astype(np.int8)
print(b.dtype)


a.dtype: float64
int8


In [19]:
arr = np.array([[0, 1, 2], [3, 4, 5]])

print('type(arr):', type(arr))
print('arr.ndim:', arr.ndim)
print('arr.dtype:', arr.dtype)
print('arr.itemsize:', arr.itemsize)
print('arr.size:', arr.size)
print('arr.nbytes:', arr.nbytes)
print('arr.T:\n', arr.T)
print('arr.shape:', arr.shape)


type(arr): <class 'numpy.ndarray'>
arr.ndim: 2
arr.dtype: int64
arr.itemsize: 8
arr.size: 6
arr.nbytes: 48
arr.T:
 [[0 3]
 [1 4]
 [2 5]]
arr.shape: (2, 3)


In [24]:
#1차원 배열 생성하기
a = np.arange(8)
print('a\n', a)

#다차원 배열로 변경하기
a.shape = (2,4)
print('shape\n', a)

#1차원 배열로 변경하기
print('flatten\n', a.flatten())

#resize 함수로 모양 변경하기
a.resize((4,2))
print('resize\n', a)


a
 [0 1 2 3 4 5 6 7]
shape
 [[0 1 2 3]
 [4 5 6 7]]
flatten
 [0 1 2 3 4 5 6 7]
resize
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [26]:
a = np.array([[0, 1, 2], [3, 4, 5]])
print('a\n', a)

b = a.transpose()
print('b\n', b)

c = a.T  #transpose=T
print('c\n', c)


a
 [[0 1 2]
 [3 4 5]]
b
 [[0 3]
 [1 4]
 [2 5]]
c
 [[0 3]
 [1 4]
 [2 5]]


In [33]:
import pandas as pd

a=pd.Series([1,2,3,4])
print(a)

b=pd.Series([1,2,3],index=['a','b','c'])
print(b)

0    1
1    2
2    3
3    4
dtype: int64
a    1
b    2
c    3
dtype: int64


In [36]:
list1 = [['허준호', '남자', '30', '183'],
         ['이가일', '여자', '24', '162'],
         ['배규민', '남자', '23', '179'],
         ['고고림', '남자', '21', '182'],
         ['이새봄', '여자', '28', '160'],
         ['이보람', '여자', '26', '163'],
         ['이루리', '여자', '24', '157'],
         ['오다현', '여자', '24', '172']]

col_names = ['이름', '성별', '나이', '키']

df = pd.DataFrame(list1, columns=col_names)
df

# 디렉토리에 CSV 파일로 저장하기
df.to_csv('./file.csv', header=True, index=False, encoding='utf-8')

# CSV 파일 읽기
df2 = pd.read_csv('./file.csv', sep=',')
df2


이름  성별  나이    키
0  허준호  남자  30  183
1  이가일  여자  24  162
2  배규민  남자  23  179
3  고고림  남자  21  182
4  이새봄  여자  28  160
5  이보람  여자  26  163
6  이루리  여자  24  157
7  오다현  여자  24  172

In [39]:
col_names = ['과목번호', '과목명', '강의실', '시간수']
list1 = [['C1', '인공지능개론', 'R1', 3],
         ['C2', '웃음치료', 'R2', 2],
         ['C3', '경영학', 'R3', 3],
         ['C4', '3D디자인', 'R4', 4],
         ['C5', '스포츠경영', 'R2', 2],
         ['C6', '예술의 세계', 'R3', 1]]

import pandas as pd
df = pd.DataFrame(list1, columns=col_names)
df.to_csv('./timetable.csv', header=True, index=False, encoding='utf-8')


In [41]:
df2=pd.read_csv('./timetable.csv',sep=',')
df2['교수']=['김예희','오정현',' 인세훈','이새봄','배유진','이가원']
df2

과목번호     과목명 강의실  시간수    교수
0   C1  인공지능개론  R1    3   김예희
1   C2    웃음치료  R2    2   오정현
2   C3     경영학  R3    3   인세훈
3   C4   3D디자인  R4    4   이새봄
4   C5   스포츠경영  R2    2   배유진
5   C6  예술의 세계  R3    1   이가원

In [42]:
max_hour=df2.groupby('강의실')['시간수'].max()
max_hour

강의실
R1    3
R2    2
R3    3
R4    4
Name: 시간수, dtype: int64

In [43]:
# 파일 복사하기
input_file = 'd:/phones.txt'  # 입력 파일 경로
output_file = 'd:/temp.txt'   # 출력 파일 경로

# 입력 파일 읽고 출력 파일에 쓰기
try:
    with open(input_file, 'r', encoding='utf-8') as infile:
        content = infile.read()

    with open(output_file, 'w', encoding='utf-8') as outfile:
        outfile.write(content)

    print(f"파일이 성공적으로 복사되었습니다: {output_file}")

except FileNotFoundError:
    print(f"입력 파일을 찾을 수 없습니다: {input_file}")
except Exception as e:
    print(f"오류가 발생했습니다: {e}")


입력 파일을 찾을 수 없습니다: d:/phones.txt
